### Get All Company
GET http://localhost:10000/api/company/

### Get One
GET http://localhost:10000/api/company/60193aa79927e71098ebb2e4

### Create One
POST http://localhost:10000/api/company/
Content-Type: application/json

{ 
    "companyName": "ANZ", 
    "cPersonName": "Bella", 
    "email": "Bella@gmail.com", 
    "sdate": "1998-06-29", 
    "edate": "2003-08-02", 
    "ifActive": true, 
    "interest1": 4, 
    "interest2": 8, 
    "interest3": 8 
    }

### Delete One
DELETE http://localhost:10000/api/company/60195e8cd3e914495070c2ee