export const CREATE_COMPANY = "CREATE_COMPANY"
export const SET_COMPANIES = "SET_COMPANIES"
export const DELETE_COMPANY = "DELETE_COMPANY"
export const UPDATE_COMPANY = "UPDATE_COMPANY"

export const LOAD_COMPANIES_LOADING = "LOAD_COMPANIES_LOADING"
export const LOAD_COMPANIES_SUCCESS = "LOAD_COMPANIES_SUCCESS"
export const LOAD_COMPANIES_ERROR = "LOAD_COMPANIES_ERROR"